import Header from "@/components/Header";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { decryptSession } from "@/lib/session";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const cookie = await (await cookies()).get("mysession")?.value;

  const session = await decryptSession(cookie);
  const strapiJwt = session?.jwt as string;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header jwt={strapiJwt} />
        <main className="bg-linear-to-tl from-indigo-100 via-purple-300 to-pink-100  ">
          {children}
        </main>
      </body>
    </html>
  );
};
export default RootLayout;
